### ISSUE TITLE
Помоги код прочитать

### ISSUE THREAD

**Issue by MaybeMeDic1** [loliland-project-team/as19#2]
package cy.jdkdigital.productivebees.common.item;

import cy.jdkdigital.productivebees.common.entity.bee.ProductiveBee;
import cy.jdkdigital.productivebees.init.ModItems;
import cy.jdkdigital.productivebees.setup.BeeReloadListener;
import cy.jdkdigital.productivebees.util.BeeCreator;
import net.minecraft.core.NonNullList;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.Block;

import javax.annotation.Nonnull;
import java.util.Map;

public class CombBlockItem extends BlockItem
{
    public CombBlockItem(Block block, Properties properties) {
        super(block, properties);
    }

    public static int getColor(ItemStack stack) {
        CompoundTag tag = stack.getTagElement("EntityTag");
        if (tag != null && tag.contains("type")) {
            CompoundTag nbt = BeeReloadListener.INSTANCE.getData(tag.getString("type"));
            if (nbt != null) {
                return nbt.getInt("primaryColor");
            }
        }
        return 0;
    }

    @Nonnull
    @Override
    public Component getName(ItemStack stack) {
        CompoundTag tag = stack.getTagElement("EntityTag");
        if (tag != null && tag.contains("type")) {
            CompoundTag nbt = BeeReloadListener.INSTANCE.getData(tag.getString("type"));
            if (nbt != null) {
                String name = Component.translatable("entity.productivebees." + ProductiveBee.getBeeName(tag.getString("type")) + "_bee").getString();
                return Component.translatable("block.productivebees.comb_configurable", name.replace(" Bee", ""));
            }
        }
        return super.getName(stack);
    }

    @Override
    public void fillItemCategory(@Nonnull CreativeModeTab group, @Nonnull NonNullList<ItemStack> items) {
        if (!this.equals(ModItems.CONFIGURABLE_HONEYCOMB.get())) {
            super.fillItemCategory(group, items);
        } else if (group == CreativeModeTab.TAB_SEARCH) {
            for (Map.Entry<String, CompoundTag> entry : BeeReloadListener.INSTANCE.getData().entrySet()) {
                String beeType = entry.getKey();
                if (entry.getValue().getBoolean("createComb")) {
                    // Add comb block
                    ItemStack combBlock = new ItemStack(ModItems.CONFIGURABLE_COMB_BLOCK.get());
                    BeeCreator.setTag(beeType, combBlock);
                    items.add(combBlock);
                }
            }
        }
    }
}

**Comment by MaybeMeDic1** [comment]
Леха

**Comment by arekusey-tyan** [comment]
А что конкретно тебя интересует?


`java
package cy.jdkdigital.productivebees.common.item;
/* import some classes */
import cy.jdkdigital.productivebees.common.entity.bee.ProductiveBee;
import cy.jdkdigital.productivebees.init.ModItems;
import cy.jdkdigital.productivebees.setup.BeeReloadListener;
import cy.jdkdigital.productivebees.util.BeeCreator;
import net.minecraft.core.NonNullList;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.Block;

import javax.annotation.Nonnull;
import java.util.Map;

public class CombBlockItem extends BlockItem
{
    /* инициализация класса CombBlockItem расширяющего класс BlockItem */
    /* Получает блок и надстройки для блока */
    public CombBlockItem(Block block, Properties properties) {
        /* вызов суперкласса */
        super(block, properties);
    }

    /**
     * функция получения int значения цвета
     * @param ItemStack stack - предмет на вход
     * @return int числовое значение цвета
     */
    public static int getColor(ItemStack stack) {
        /* Получение NBT-тега EntityTag предмета stack */
        CompoundTag tag = stack.getTagElement("EntityTag");
        if (tag != null && tag.contains("type")) {
            /* Получение NBT-тега предмета stack */
            CompoundTag nbt = BeeReloadListener.INSTANCE.getData(tag.getString("type"));
            if (nbt != null) {
                return nbt.getInt("primaryColor");
            }
        }
        return 0;
    }

    /**
     * функция получения имени предмети
     * @param ItemStack stack - предмет на вход
     * @return Component имя предмета (локализированное)
     */
    @Nonnull
    @Override
    public Component getName(ItemStack stack) {
        CompoundTag tag = stack.getTagElement("EntityTag");
        if (tag != null && tag.contains("type")) {
            CompoundTag nbt = BeeReloadListener.INSTANCE.getData(tag.getString("type"));
            if (nbt != null) {
                String name = Component.translatable("entity.productivebees." + ProductiveBee.getBeeName(tag.getString("type")) + "_bee").getString();
                return Component.translatable("block.productivebees.comb_configurable", name.replace(" Bee", ""));
            }
        }
        return super.getName(stack);
    }

    /**
     * функция добавления в творческую вкладку
     * @param CreativeModeTab group - вкладка креатива
     * @param NonNullList<ItemStack> items - предметы
     * @return
     */
    @Override
    public void fillItemCategory(@Nonnull CreativeModeTab group, @Nonnull NonNullList<ItemStack> items) {
        if (!this.equals(ModItems.CONFIGURABLE_HONEYCOMB.get())) {
            super.fillItemCategory(group, items);
        } else if (group == CreativeModeTab.TAB_SEARCH) {
            for (Map.Entry<String, CompoundTag> entry : BeeReloadListener.INSTANCE.getData().entrySet()) {
                String beeType = entry.getKey();
                if (entry.getValue().getBoolean("createComb")) {
                    // Add comb block
                    ItemStack combBlock = new ItemStack(ModItems.CONFIGURABLE_COMB_BLOCK.get());
                    BeeCreator.setTag(beeType, combBlock);
                    items.add(combBlock);
                }
            }
        }
    }
}
`

ну как-то так. 

Для полного понимания уточни, что именно тебе надо.
